# Main ideas

## System Equilibrium Equations
Let us denote as $P(\bar{w}, \bar{s})$ the probability to have $\bar{w}$ items waiting and $\bar{s}$ the items in service.

The equilibrium equations are as follows:

For $n>k$
$$\left (\sum_{i=1}^N \lambda_i +  \sum_{i=1}^N s_i\mu_i \right) P(\bar{w}, \bar{s}) = \sum_{i=1}^N \lambda_i P(\bar{w}-e_i, \bar{s}) + \sum_{i=1}^N \sum_{j=1}^N \frac{w_i+1}{|\bar{w}|+1} (s_j + 1 - e_{ij})\mu_j P(\bar{w}+e_i, \bar{s}-e_i+e_j)$$

For $n=k$
$$\left (\sum_{i=1}^N \lambda_i +  \sum_{i=1}^N s_i\mu_i \right) P(\bar{0}, \bar{s}) = \sum_{i=1}^N \lambda_i P(\bar{0}, \bar{s}-e_i) + \sum_{i=1}^N \sum_{j=1}^N (s_j + 1 - e_{ij})\mu_j P(e_i, \bar{s}-e_i+e_j)$$

For $0<n<k$
$$\left (\sum_{i=1}^N \lambda_i +  \sum_{i=1}^N s_i\mu_i \right) P(\bar{0}, \bar{s}) = \sum_{i=1}^N \lambda_i P(\bar{0}, \bar{s}-e_i) + \sum_{j=1}^N (s_j + 1)\mu_j P(0, \bar{s}+e_j)$$

For $0=n$
$$\sum_{i=1}^N \lambda_i P(\bar{0}, \bar{0}) = \sum_{j=1}^N \mu_j P(0, e_j)$$

## Product-Form Solution
The steady state probabilities $P(\bar{w}, \bar{s})$ can be expressed as:
$$P(\bar{w}, \bar{s}) =  |\bar{w}|!  \prod_{i=1}^N \frac{\alpha_i^{w_i}}{w_i!} P_n(\bar{s})$$

Denote further the vector that contains all  components $P_n(\bar{s})$ as $\mathbf{P}_n$ 


The equilibrium equations can be rewritten as:

For $n>k$
$$\mathbf{A}_0 \mathbf{P}_n = \mathbf{\Lambda} \mathbf{P}_{n-1} + \mathbf{A}_1 \mathbf{P}_{n+1}$$
where $\mathbf{A}_0$ is a diagonal matrix with $\sum_{i=1}^N \lambda_i +  \sum_{i=1}^N s_i\mu_i$ on each diagonal cell corresponding to $\bar{s}$. <br>In $\mathbf{A}_1$ each element corrsponding to $(\bar{s}, \bar{s}-e_i+e_j)$ will be:
$\sum_{i=1}^N \sum_{j=1}^N \alpha_i (s_j + 1 - e_{ij})\mu_j$ 

For $n=k$
$$\mathbf{A}_0 \mathbf{P}_{n} = \sum_{i=1}^N \lambda_i P(\bar{0}, \bar{s}-e_i) + \mathbf{A}_1 \mathbf{P}_{n+1}$$

For $0<n<k$
$$\left (\sum_{i=1}^N \lambda_i +  \sum_{i=1}^N s_i\mu_i \right) P(\bar{0}, \bar{s}) = \sum_{i=1}^N \lambda_i P(\bar{0}, \bar{s}-e_i) + \sum_{j=1}^N (s_j + 1)\mu_j P(0, \bar{s}+e_j)$$

For $0=n$
$$\sum_{i=1}^N \lambda_i P(\bar{0}, \bar{0}) = \sum_{j=1}^N \mu_j P(0, e_j)$$

## Computing Steady-State probabilities
### Steady-State probabilities for $n>k$
The equation $\mathbf{A}_0 \mathbf{P}_n = \mathbf{\Lambda} \mathbf{P}_{n-1} + \mathbf{A}_1 \mathbf{P}_{n+1}$ can be solved using Martix-Geometric approach and the probability vectors $\mathbf{P}_n$ can be expressed as the following geometric series:
$$\mathbf{P}_n = \mathbf{Z} \mathbf{P}_{n-1} = \mathbf{Z}^{n-k} \mathbf{P}_{k}$$

The matrix $\mathbf{Z}$ is the solution of the following quadratic matxix equation:
$$\mathbf{A}_0 \mathbf{Z} = \mathbf{\Lambda}  + \mathbf{A}_1 \mathbf{Z}^2$$
and can be found using eigenvalue/vector formulations or using the follwoing iterative procedure.

Define 
    $$\mathbf{Z}_l = \mathbf{A}_0^{-1} (\mathbf{\Lambda} + \mathbf{A}_1 \mathbf{Z}_{l-1}^2)$$
Then if we start with $\mathbf{Z_0}=\mathbf{0}$, the matrix $\mathbf{Z}$ will be:
$$\mathbf{Z} = \lim_{l\to \infty} \mathbf{Z}_{l}$$

### Steady-State probabilities for $n\le k$
The probability vectors $\mathbf{P}_n$ for $n\le k$ will be computed as:
$$ \mathbf{P}_n = \mathbf{Q}_{n-1} \mathbf{P}_{n-1} = \mathbf{Q}_{n-1} \cdots \mathbf{Q}_{0} \mathbf{P}_{0} $$
The matrices $\mathbf{Q}_{n}$ are such that the following equations are satisified:
$$\mathbf{A}_{0,n} \mathbf{Q}_{n} = \mathbf{\Lambda}_n  + \mathbf{A}_{1,n} \mathbf{Q}_{n+1}\mathbf{Q}_{n}$$
where:
 - $\mathbf{\Lambda}_n$ is and $dim(n) \times dim(n-1)$ matrix corresponding to the terms with $ \sum_{i=1}^N \lambda_i P(\bar{0}, \bar{s}-e_i)$
 - $\mathbf{A}_{0,n}$ is and $dim(n) \times dim(n)$ matrix corresponding to the terms with $\left (\sum_{i=1}^N \lambda_i +  \sum_{i=1}^N s_i\mu_i \right) P(\bar{0}, \bar{s}) $
 - $\mathbf{\Lambda}_n$ is and $dim(n) \times dim(n+1)$ matrix corresponding to the terms with $ \sum_{j=1}^N (s_j + 1)\mu_j P(0, \bar{s}+e_j)$

The matrix $\mathbf{Q}_{n}$ will be computed iteratively as:
- $\mathbf{Q}_{k} = \mathbf{Z}$
- $\mathbf{Q}_n = (\mathbf{A}_{0,n} - \mathbf{A}_{1,n} \mathbf{Q}_{n+1})^{-1} \mathbf{\Lambda}_n$, for $n<k$


After that we can compute $\mathbf{P}_0$ using normalization equation:
$$ \mathbf{P}_0 = \left (1 + \mathbf{E}_1  \mathbf{Q}_0 + \mathbf{E}_2 \mathbf{Q}_1 \mathbf{Q}_0 + \cdots + \mathbf{E}_k (\mathbf{I} - \mathbf{Z} )^{-1} \mathbf{Q}_{k-1} \cdots \mathbf{Q}_0 \right )^{-1}$$ 

the the system state propoabilities as:
- $\mathbf{P}_n = \mathbf{Q}_{n-1} \mathbf{P}_{n-1}$, for $n\le k$
- $\mathbf{P}_n = \mathbf{Z} \mathbf{P}_{n-1} $, for  $n > k$



## Computing $E[N_i]$ and $Var[N_i]$

$E[N_i]= E[Q_i] + Q[S_i] = E[Q_i] + {\lambda_i \over \mu_i}$

$E[Q_i]= \alpha_i \mathbf{1}^T (\mathbf{I} - \mathbf{Z} )^{-2} \mathbf{Z} \mathbf{P}_{k}$

$Var[N_i]= E[Q^2_i] + E[Q_i\cdot S_i] + E[S_i^2] - E[N_i]^2$

$Var[Q_i] = E[Q_i^2] - E[Q_i]^2$

$E[Q_i^2] = E[Q_i(Q_i-1)] + E[Q_i]$

$E[Q_i(Q_i-1)] = 2 \alpha^2_i \mathbf{1}^T (\mathbf{I} - \mathbf{Z} )^{-3} \mathbf{Z}^2 \mathbf{P}_{k}$

$E[Q_i S_i] = \alpha_i \mathbf{\chi}_{k,S} (\mathbf{I} - \mathbf{Z} )^{-2} \mathbf{Z} \mathbf{P}_{k}$ - where $\mathbf{\chi_S}$ are the vectors containing number of items of each type in the service

$E[S^2_i] = \sum_{n=1}^{k-1} \mathbf{\chi}^2_{n,S} \mathbf{P}_{n} + \mathbf{\chi}^2_{k,S} (\mathbf{I} - \mathbf{Z} ) \mathbf{P}_{k} $ 


$Var[N_2] = E[Q_i(Q_i-1)] + E[Q_i] + 2E[Q_i S_i] + E[S^2_i]$



------------------

# Codes

In [84]:
# initialize libraries
import numpy as np

In [85]:
# Define the generator that will generate all possible assignments of classes to servers, without permutations
def generateVectorsFixedSum(m,n):
    # generator for all combinations of $w$ for given number of servers and classes
    if m==1:
        yield [n]
    else:
        for i in range(n+1):
            for vect in generateVectorsFixedSum(m-1,n-i):
                yield [i]+vect

In [86]:
# Example
mClasses = 3
nServers = 3

# to produce the combinations
# the generators should be called in a loop
# the loop will stop when all possible combinations are generated
# the vectors contain numbers of customers of each class in the system
for i, vec in enumerate(generateVectorsFixedSum(mClasses, nServers)):
    print i, vec
    
# 'enumerate' produces two values, the generated vector and its number in the whole sequence.
# 'enumerate' will be used later to produce mapping between the states of the system and matrix elements

0 [0, 0, 3]
1 [0, 1, 2]
2 [0, 2, 1]
3 [0, 3, 0]
4 [1, 0, 2]
5 [1, 1, 1]
6 [1, 2, 0]
7 [2, 0, 1]
8 [2, 1, 0]
9 [3, 0, 0]


In [87]:
# create some data
mClasses = 3
nServers = 3
lamda = np.array([3.0, 4.0, 5.0]) #np.linspace(1,2,mClasses)
mu = 5*np.ones(mClasses) #np.linspace(2,1,mClasses)
print lamda
print mu
print sum(lamda/mu)
assert sum(lamda/mu)<nServers # ensure stability

[ 3.  4.  5.]
[ 5.  5.  5.]
2.4


In [88]:
# initialize \Lamda and \alpha
lambdaTot = sum(lamda)
alpha = lamda/lambdaTot

In [89]:
# create mapping between the combination vectors and matrix columns/rows
idx_map = dict([ (tuple(vect), i) for i, vect in enumerate(generateVectorsFixedSum(mClasses, nServers)) ])
# need to use tuple here as 'list' cannot be as a key
i_map   = dict([(idx_map[idx], list(idx)) for idx in idx_map ]) 
# need to use list here as 'tuple' cannot be modified as will be need further

In [90]:
# function to get matrix index based on the system state
def getIndexDict(idx, idx_map):
    try:
        return idx_map[tuple(idx)]
    except KeyError:
        return -1

In [91]:
# generate matrices A_0 and A_1
q_max = len(idx_map)
A0 = np.zeros((q_max,q_max))  #corresponds to terms with i items in queue
A1 = np.zeros((q_max,q_max))  #corresponds to terms with i+1 items in queue
for i, idx in i_map.items():
    #diagonal term
    A0[i,i] += 1 + np.sum(idx*mu)/lambdaTot

    #term corresponding to end of service for item j1, start of service for j2
    for j1 in xrange(mClasses):
        for j2 in xrange(mClasses):
            idx[j1] += 1; idx[j2] -= 1
            i1 = getIndexDict(idx, idx_map)  #convert 'list' back to tuple to use it as a key
            if i1>=0: A1[i,i1] += alpha[j2]/lambdaTot*idx[j1]*mu[j1]
            idx[j1] -= 1; idx[j2] += 1

In [100]:
# compute matrix Z iteratively
eps = 0.0000000000001
I = np.eye(q_max) # produces identity matrix
Z_prev = np.zeros((q_max, q_max)) 
delta=1
A0_inv = np.linalg.inv(A0)
while delta>eps:
    Z = np.dot(A0_inv, I + np.dot(A1, np.dot(Z_prev, Z_prev)))  #invA0*(I+A1*Z*Z)
    delta = np.sum(np.abs(Z-Z_prev))
    Z_prev=Z

In [93]:
# generate Q matrices, it will be stored in a list
Q = []
idxMat = [] # matrix with server occupancy for each system state, will be used in computing the system parameters
Q.insert(0, Z[:])
idxMat.insert(0, np.array([x for x in i_map.values()]))

In [94]:
idx_map_nplus = idx_map #dict([ (tuple(vect), i) for i, vect in enumerate(generateVectorsFixedSum(mClasses, nServers)) ])
i_map_nplus   = i_map #dict([(idx_map_nplus[idx], list(idx)) for idx in idx_map_nplus ])
q_max_nplus   = len(idx_map_nplus)

idx_map_n = idx_map_nplus
i_map_n   = i_map_nplus
q_max_n   = q_max_nplus

A1_n = A1[:]

for n in range(nServers,0,-1):
    idx_map_nminus = dict([ (tuple(vect), i) for i, vect in enumerate(generateVectorsFixedSum(mClasses, n-1)) ])
    i_map_nminus   = dict([(idx_map_nminus[idx], list(idx)) for idx in idx_map_nminus ])
    q_max_nminus   = len(idx_map_nminus)

    L_n = np.zeros((q_max_n,q_max_nminus))  #corresponds to terms with i items in queue
    A0_n = np.zeros((q_max_n,q_max_n))  #corresponds to terms with i items in queue
    for i, idx in i_map_n.items():

        #diagonal term
        A0_n[i,i] += 1 + np.sum(idx*mu)/lambdaTot

        #term corresponding to arrival of item item j1
        for j2 in xrange(mClasses):
            idx[j2] -= 1
            i2 = getIndexDict(idx, idx_map_nminus) 
            if i2>=0: L_n[i,i2] += alpha[j2]
            idx[j2] += 1

    # Q_n = (A_0 - A_1*Q_{n+1})^{-1}*L_n
    Q.insert(0, np.dot(np.linalg.inv(A0_n-np.dot(A1_n, Q[0])), L_n)) 

    idx_map_nplus = idx_map_n
    i_map_nplus   = i_map_n
    q_max_nplus   = q_max_n

    idx_map_n = idx_map_nminus
    i_map_n   = i_map_nminus
    q_max_n   = q_max_nminus
    idxMat.insert(0, np.array([x for x in i_map_n.values()]))    


    A1_n = np.zeros((q_max_n,q_max_nplus))  #corresponds to terms with i+1 items in queue
    for i, idx in i_map_n.items():
        #term corresponding to end of service for item j1
        for j1 in xrange(mClasses):
            idx[j1] += 1
            i1 = getIndexDict(idx, idx_map_nplus) 
            if i1>=0: A1_n[i,i1] += idx[j1]*mu[j1]/lambdaTot
            idx[j1] -= 1

In [95]:
# compute the P_n for n<k and normalize it such that sum(P_n) = 1
P = []
P.append([1.0])

sm = 1.0
for n in xrange(nServers):
    P.append(np.dot(Q[n],P[-1]))
    sm += sum(P[-1])

sm += sum(np.dot(np.linalg.inv(np.eye(len(P[-1])) - Z), np.dot(Z,P[-1])))

for p in P: p[:] /= sm  #normalization

In [96]:
# compute totals needed for the E[Q_i] - marginal distributions
inv1minZ = np.linalg.inv(np.eye(len(P[-1])) - Z)
EQTotal = sum(np.dot(np.dot(np.dot(inv1minZ,inv1minZ), Z),P[-1]))
EQQmin1Total = 2*sum(np.dot(np.dot(np.dot(np.dot(np.dot(inv1minZ,inv1minZ),inv1minZ), Z), Z), P[-1]))
EQ2Total = EQQmin1Total + EQTotal

# compute 1st and 2nd marginal moments of the numbers in the queue E[Q_i] and E[Q_i^2]
EQ = alpha*EQTotal
EQQmin1 = alpha*alpha*EQQmin1Total
EQ2 = EQQmin1 + EQ

In [97]:
# compute 1st and 2nd marginal moments of the numbers in the system E[N_i] and E[N_i^2]
ENTotal = EQTotal + sum(lamda/mu)
EN = EQ + lamda/mu

# TODO compute the E[N_i^2]
ES2 = np.zeros(mClasses)
for (p, idx) in zip(P[:-1], idxMat[:-1]):
    ES2 += np.dot(p, idx**2)
ES2 += np.dot(np.dot(inv1minZ, P[-1]), idxMat[-1]**2)

ESq = alpha*np.dot(np.dot(np.dot(np.dot(inv1minZ,inv1minZ), Z),P[-1]), idxMat[-1])

EN2 = EQ2 + 2*ESq + ES2


In [98]:
# compute marginal variances of the numbers in the queue Var[Q_i] and in the system Var[N_i] 
VarQTotal = EQ2Total - EQTotal**2
VarQ = EQ2 - EQ**2

VarN = EN2 - EN**2



In [99]:
print EN
print VarN

[ 1.24719101  1.66292135  2.07865169]
[ 2.21979548  3.39199596  4.78033077]
